### ISSUE TITLE
Error 404 on bubbles page

### ISSUE THREAD

**Issue by EwelinaLasowy** [blumilksoftware/website#146]
**Describe the bug**
Our bubbles generator works as expected, but console throws error 404.

**To Reproduce**
1. Go to www.blumilk.pl/bubble/25
2. Open developer tools in the browser
3. Seen 404 error in the console, but bubbles generator works

**Expected behavior**
I don't want to see 404 error in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/56546832/153556241-a2a6a5eb-9661-485b-9e20-2c470b152c50.png)

**Desktop:**
- OS: kubuntu 
- Browser: Google Chrome
- Version: 98.0.4758.80

**Comment by krzysztofrewak** [comment]
This is an easter egg page and this 404 behaviour is a bug in GitHub Pages. I'm closing it due to the low social harmfulness. ;)
