### ISSUE TITLE
Missing status code for index page

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/website#158]
For every page like About or Contact the GHP returns a proper response status code, 200 or 301:

![obraz](https://user-images.githubusercontent.com/10898728/167309708-0aa4af6f-3951-4610-9f37-736bb1f3ca27.png)

But for main page it's a empty value:

![obraz](https://user-images.githubusercontent.com/10898728/167309725-76c56c05-6548-4962-ad60-54d8ceb95147.png)

I am pretty sure that's affecting our Google search position:

![obraz](https://user-images.githubusercontent.com/10898728/167309746-2048b0a4-8af0-4a3f-87d3-2353f949bd54.png)

AC: index page should be loaded with 200/301 status code.

This is probably related to #127.

**Comment by kamilpiech97** [comment]
I see that when I open main page:
![obraz](https://user-images.githubusercontent.com/29115024/172993159-9e3cf349-6986-4817-81f7-611a85c66b8a.png)

**Comment by krzysztofrewak** [comment]
Huh, it must have fix itself. I'm closing this issue.
