### ISSUE TITLE
Website description

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/website#165]
We are missing main page description:

![obraz](https://user-images.githubusercontent.com/10898728/173029625-7e38c70c-f4a4-47e4-ac2b-e9d3a0dedfa1.png)

I think it should be added in default file, somewhere here: https://github.com/blumilksoftware/website/blob/main/public/index.html

@kamilpiech97, do you know if we can add it in Polish and English at the same time?

**Comment by kamilpiech97** [comment]
I see description for main page.
![obraz](https://user-images.githubusercontent.com/29115024/177094574-d4b94c92-49fb-4eae-9b20-7b1ce2fdb6db.png)

We can do that but we must separate in link one from two languages - `https://www.blumilk.pl/pl` or `https://www.blumilk.pl/en` and end that [issue](https://github.com/blumilksoftware/website/issues/97).
