### ISSUE TITLE
UX writing improvements

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/website#183]
I would like to review all texts on our website and improve them UX-wise wherever possible.

**Comment by Shimnom1** [comment]
I will like to be a part of the team for this project.

**Comment by krzysztofrewak** [comment]
> I will like to be a part of the team for this project.

Assignee @EwelinaLasowy is already taking care of it. How would you like to contribute here? Maybe you could wait for her pull request and propose your suggestions?
