### ISSUE TITLE
Migrate to Google Analytics 4

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/website#197]
I received an e-mail from Google:

> Twoje konto Google Analytics wymaga podjęcia natychmiastowego działania. Nasze rozwiązanie analityczne nowej generacji, Google Analytics 4, zastępuje Universal Analytics. Od 1 lipca 2023 r. standardowe usługi w Universal Analytics przestaną przetwarzać nowe dane. Jeśli używasz Google Ads, oznacza to, że dane z Universal Analytics wykorzystywane w kampaniach reklamowych zaczną się stopniowo zerować, co może mieć wpływ na skuteczność reklam. Zdecydowanie zalecamy wykonanie czynności przedstawionych w szczegółowym przewodniku, aby jak najszybciej przejść na Google Analytics 4.
> 
> SKONFIGURUJ GOOGLE ANALYTICS 4
> 
> Aby gromadzić dane i zapewnić ciągłość działania Google Analytics 4, należy koniecznie już teraz skonfigurować usługę. Pozwoli to rozpocząć gromadzenie w Google Analytics 4 właściwych danych odpowiadających Twoim potrzebom. Unikniesz także zakłóceń w działaniu kampanii Google Ads, które nadal korzystają z konwersji i list odbiorców z Universal Analytics.
> 
> O ile ta opcja nie została wyłączona na Twoim koncie, już skonfigurowaliśmy lub niedługo skonfigurujemy dla Ciebie usługę w Google Analytics 4 z podstawowymi ustawieniami, w tym wybranymi celami i połączeniami z Google Ads przeniesionymi z Universal Analytics. Nie możemy jednak przenieść niektórych ustawień z bieżącej konfiguracji Universal Analytics, takich jak niestandardowe wymiary i dane. Jeśli teraz dostosujesz konfigurację Google Analytics 4, będziesz mieć pewność, że gromadzisz właściwe dane powiązane z odpowiednimi konwersjami, listami odbiorców i innymi danymi Analytics, które są dla Ciebie najbardziej przydatne. Dzięki temu będziesz nadal mierzyć najwartościowsze działania i prowadzić bardziej efektywne kampanie reklamowe.
> 
> Aby dowiedzieć się, jakich zmian w usłudze Universal Analytics możesz oczekiwać w przyszłym miesiącu, odwiedź Centrum pomocy
> 
> Pozdrawiamy
> Zespół Google Analytics

It look like we need to do something about it before the end of the month.

**Comment by KarolZygadlo** [comment]
It is already configured for our basic needs, we using the newer version of the google analytics, so there is nothing for us to change

**Comment by krzysztofrewak** [comment]
Thanks!
