### ISSUE TITLE
Implementing new desing of the site

### ISSUE THREAD

**Issue by Letha0** [blumilksoftware/website#209]
Rozpoczynamy prace na wdrożeniem nowego widoku strony firmy.
Bazować będziemy na stworzonym przez grafika design: https://xd.adobe.com/view/26f66876-cddd-469c-8b1f-b991dec40e55-73a5/grid
W razie potrzeby większej ilości informacji swoje pytania warto kierować do Katarzyny Nowak oraz Eweliny Skrzypacz.

Do zapamiętania:
- strona ma być docelowo wielojęzyczna, na początek jednak zakładamy dwa języki: polski i angielski,
- ma być też mobilna wersja strony: https://xd.adobe.com/view/48e3dd96-96c0-4801-aee3-93a97687467e-1db0/grid

Widoki:

- [x] #210
- [x] #211
- [x] #212
- [x] #213
- [x] #214
- [x] #215
- [x] #216
- [x] #217
- [x] #218

**Comment by AleksandraKozubal** [comment]
Everything has been done, except #214 that was closed because it was no longer needed.
