### ISSUE TITLE
Case study - details page

### ISSUE THREAD

**Issue by Letha0** [blumilksoftware/website#213]
Strona ze szczegółami case studies
Link: https://xd.adobe.com/view/26f66876-cddd-469c-8b1f-b991dec40e55-73a5/screen/06a2e316-ea87-4408-91b0-dfa7260387ec/ 
Może być tak, że każde case study będzie wyglądało inaczej - więc trzeba to dobrze przemyśleć.
Do przemyślenia i przegadania z Kasią, jak mielibyśmy tym zarządzać.
(Ponieważ case studies nie będą się często zmieniać- to może jako gotowe strony do edycji w html?)
Temat jeszcze do szerszego omówienia

![obraz](https://github.com/blumilksoftware/website/assets/51294636/3b3e2836-e72c-43a3-9a0f-78fbef188f51)

**Comment by AleksandraKozubal** [comment]
Ustalono, że pod każde case study będzie robiony komponent indywidualnie, w zależności od treści, którą będziemy chcieli przedstawić.
Flow: przygotowanie treści merytorycznej do case study -> przygotowanie projektu układu treści w komponencie -> dodanie komponentu -> dodanie case study w panelu admina
