### ISSUE TITLE
Partners page

### ISSUE THREAD

**Issue by Letha0** [blumilksoftware/website#214]
Należy zaimplementować stronę odnośnie partnerów firmy
Link: https://xd.adobe.com/view/26f66876-cddd-469c-8b1f-b991dec40e55-73a5/screen/40b8b8b1-7257-4b42-8b50-0ef456578fd5

![obraz](https://github.com/blumilksoftware/website/assets/51294636/33fc0467-5d61-4755-9e15-ee9da97ffdd9)

**Comment by AleksandraKozubal** [comment]
New design doesn't include partners page.
