### ISSUE TITLE
[SEO] Images alt tags

### ISSUE THREAD

**Issue by kamilpiech97** [blumilksoftware/website#235]
We should implement for all images on our website propper alt tags. Its additional plus in `SEO` optimization.

Example:
`<img src="img_girl.jpg" alt="Girl in a jacket">`

Images should be also properly optimized - I mean should have very small weight but that should not mainly influence on theirs quality. `WebP` foramt is very good for optimizing images - Google provides a lot of advice on optimizing images and the `WebP` format is one of the recommended ones.

[Lighthouse](https://chromewebstore.google.com/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=pl) should be good tool to checking images and related stuff around SEO.

**Comment by AleksandraKozubal** [comment]
Closed by #332
