### ISSUE TITLE
Remembering selected locale

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/website#24]
Right now translations are initialized in `main.js` accordingly to Svelte docs:
```js
init({
  fallbackLocale: 'en',
  initialLocale: getLocaleFromNavigator()
})
```

It's nice, but when user refreshes page, translations are going back to navigator locale. I would like to store this data in some cookie or whatever.

**Comment by kamilpiech97** [comment]
I think cookie or local storage will be okay solution.
