### ISSUE TITLE
[About page] When I hover on images, they overlapped a bit

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/website#248]
It's a tricky a bit, because on @AleksandraKozubal laptop it seems that the problem with overlapping images doesn't exist, but  on my laptop it doesn't - please look at the video below.

https://github.com/blumilksoftware/website/assets/56546832/68d2296c-6f09-496a-9669-e3780113cd49

When we will have some beta, more people can test it and after that we will know that is something to fix or it's just mine laptop

**Comment by AleksandraKozubal** [comment]
@EwelinaSkrzypacz I guess that this problem was solved in #247?

**Comment by EwelinaSkrzypacz** [comment]
For now I don;t have this problem, so I'm closing this issue.
