### ISSUE TITLE
Beta deployment

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/website#264]
I need current `main` deployed to beta server. AC:
- site should be available under https://dev.website.blumilk.pl/
- it should be behind authelia

**Comment by mtracz** [comment]
@krzysztofrewak 

> it should be behind authelia

One factor should be fine I think so? 
Or you would like to have two factor here?

**Comment by mtracz** [comment]
And the second question did you configured domain's A record to point to the our server already?

**Comment by krzysztofrewak** [comment]
One factor is enough. Domain is configured.
