### ISSUE TITLE
Add WYSIWYG editor to activity description 

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/website#270]
As we started writing activities, we came to conclusion that we need something more than textarea for activity description. We need WYSIWYG editor - we want to make newlines, add links, style text and so on.

**Comment by AleksandraKozubal** [comment]
@EwelinaSkrzypacz  Do we want to add images here?

**Comment by EwelinaSkrzypacz** [comment]
For now, I don't think so that we need this
