### ISSUE TITLE
Locale switch doesn't work on beta

### ISSUE THREAD

**Issue by AleksandraKozubal** [blumilksoftware/website#287]
There is a problem with switching language on https://dev.website.blumilk.pl/
PL/EN options have always the same `href`, the same as currently selected lang.
This bug only happens on beta, on localhost everything works just fine.

Dropdown options are placed for desktop [here](https://github.com/blumilksoftware/website/blob/7076ad788b8477008e710f439d04bc4e970f6f4c/resources/views/layout/navigation.blade.php#L53) and for mobile [here](https://github.com/blumilksoftware/website/blob/7076ad788b8477008e710f439d04bc4e970f6f4c/resources/views/layout/navigation.blade.php#L128).

**Comment by mtracz** [comment]
@AleksandraKozubal 
Could you remove `authelia@file,` from here
https://github.com/blumilksoftware/website/blob/main/environment/prod/deployment/beta/docker-compose.beta.yml#L35
deploy and test if this issue is related with Authelia or not?
