### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/website#64]
It would be nice to add some instructions to robots how to deal with our site. Something like this: https://developers.google.com/search/docs/advanced/robots/create-robots-txt?hl=en

**Comment by krzysztofrewak** [comment]
Oh, my bad, I shouldn't give your an accept. 'robots.txt` file is in wrong directory. To publish it properly, it should be in `public`.

**Comment by EwelinaLasowy** [comment]
Okay, I' ll fix that in a minute.
