### ISSUE TITLE
English version website fix

### ISSUE THREAD

**Issue by kamilpiech97** [blumilksoftware/website#97]
We need change english version of the webiste. How? Its simple, URL must have en prefix when somebody switch language.
Google will be index site in two languages, now we have not difference between polish and english language.

**Comment by krzysztofrewak** [comment]
I'll take it. Right now I have no idea if Svelte i18n allows us to do this easy way.

**Comment by krzysztofrewak** [comment]
And it can be done with #24 in one PR probably.

**Comment by kamilpiech97** [comment]
> And it can be done with #24 in one PR probably.

Not at all, because we do not have information about the language in the link - only in local memory, which robots cannot see and recognize.

**Comment by krzysztofrewak** [comment]
I started working with that here: https://github.com/blumilksoftware/website/tree/%2397-i18n-refactor but I don't know how to finish this. Maybe you could start when I stuck?
